### ISSUE TITLE
config properties are undefined

### ISSUE THREAD

**Issue by PatrickSTM** [koole/react-sanctum#10]
I am initializing the Sanctum with the following code:

```
import { Sanctum } from "react-sanctum";
const sanctumConfig = {
  api_url: "https://example.com",
  csrf_cookie_route: "sanctum/csrf-cookie",
  singin_route: "login",
  signout_route: "logout",
  user_object_route: "api/user"
}

ReactDOM.render((
  <Sanctum config={sanctumConfig}>
    <Router >
        <Switch>
          <Route exact={true} path="/queues" component={Queues} />
          <Route exact={true} path="/queues/:id" component={Queue} />
          <Route exact={true} path="/login" component={Login} />
        </Switch>
      </Router>
  </Sanctum>),
  document.getElementById('root')
);

```
In my Login-Component, I am trying to use the signIn-Method:
```
import { SanctumContext, withSanctum } from 'react-sanctum';

export default function LoginPage()
{
    const [email, setEmail] = useState("");
    const [password, setPassword] = useState("");
    const [loginSuccess, setLoginSuccess] = useState(false);
    
    const context = useContext(SanctumContext);
    console.log(context.signIn("test", "Test", false));

   return (...)
}
```

My Console shows the following error:

Access to XMLHttpRequest at 'https://example.com/undefined' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

As you can see, I set my sign_in route to "login",  but he isn't calling the  correct url (example.com/login). Instead, he is calling example.com/undefined.

I also tried it with the withSanctum-way, but there is the same behaviour...

**Comment by koole** [comment]
I tried reproducing your issue, and I think I've found the problem. There's a typo in your config, you wrote `singin_route: "login",` instead of `signin_route: "login",`. Changing that should fix it 👍
