### ISSUE TITLE
You can use the fetch API instead of Axios

### ISSUE THREAD

**Issue by jeroen2002** [koole/react-sanctum#12]
Javascripts build in Fetch API is very good! And you don't need a package as Axios.

**Comment by koole** [comment]
You're right! However the project this package was initially built for was using Axios, hence this package was built using Axios.

Another advantage is that we can set easily Axios to use the sanctum cookies for every request by just enabling `axios.defaults.withCredentials = true;`. I think, but I'm not completely sure, if you wanted to do the same thing with Fetch you would have to add `credentials: 'include'` every time to want to make a request.
