### ISSUE TITLE
Redirect if not authenticated?

### ISSUE THREAD

**Issue by timvonwerne** [koole/react-sanctum#13]
Hello there!
I am trying to implement this into a new project. Is it possible to redirect the user in case he is not authenticated?

This is what I tried so far but obviously, React is not waiting for react-sanctum to call the API and set the state of the user object.

Is there any way I can redirect the user **after** the authenticated prop is set as it should be?

```
class App extends Component {
  render() {
    if (this.props.authenticated) {
      return <MyComponent />;
    } else {
      window.location.href = 'http://localhost:8000/login'
    }
  }
}
```

**Comment by koole** [comment]
Hi! Authenticated is null by default, and after calling the API it will be either `true` or `false`. So instead of just having an else statement, you could have:

```js
if (this.props.authenticated === true) {
  // Signed in
  return <MyComponent />;
} else if (this.props.authenticated === false) {
  // Signed out
  window.location.href = "http://localhost:8000/login";
} else {
  // API call hasn't finished
  return <LoadingComponent />;
}

```
