### ISSUE TITLE
Version 2.1.3 still has the Children type error

### ISSUE THREAD

**Issue by DaLukasTI** [koole/react-sanctum#150]
Hi there,
Awesome package!

But I ran into an issue with react 18.2 
While using version 2.1.3 i still get the following error:
``` TS2322: Type '{ children: Element; config: { apiUrl: string; csrfCookieRoute: string; signInRoute: string; signOutRoute: string; userObjectRoute: string; }; checkOnInit: true; }' is not assignable to type 'IntrinsicAttributes & Props'.   Property 'children' does not exist on type 'IntrinsicAttributes & Props'. ```

If I take a look at the Sanctum.d.ts it still looks like this:
```import React from "react";
import { AxiosInstance } from "axios";
interface Props {
    config: {
        apiUrl: string;
        csrfCookieRoute: string;
        signInRoute: string;
        signOutRoute: string;
        userObjectRoute: string;
        twoFactorChallengeRoute?: string;
        axiosInstance?: AxiosInstance;
    };
    checkOnInit?: boolean;
}
declare const Sanctum: React.FC<Props>;
export default Sanctum;
```

Whilst on your Github there should indeed be a Children element in the props. I'm on version 2.1.3 for sure as my yarn.lock states:
```
react-sanctum@^2.1.3:
  version "2.1.3"
  resolved "https://registry.yarnpkg.com/react-sanctum/-/react-sanctum-2.1.3.tgz#acf8f97bb482e1f38130baddf42e92a4b7fbedee"
  integrity sha512-J4MPrlSkgY012H1CPQBdQrUFkRkZWMPkSI+HARzw0eigMP1wCAo7hcZNCx153dzIq2Pi9LcbtCeQ0QsYIouYmw==
  dependencies:
    axios "^0.26.0" 
```

Any way to fix that?

**Comment by koole** [comment]
Yeah, you're right, I wrote a fix and pushed it to GitHub, however I had heard of nobody having issues yet so I just hadn't taken the time to release a new version of the package yet. Apparently I should have, haha!

Anyway, the fix has now been published in v2.2.0!
