### ISSUE TITLE
Does this work with Sanctum tokens?

### ISSUE THREAD

**Issue by CitizenBeta** [koole/react-sanctum#262]
I've got a react app that will be running on a different domain from my api. My understanding is that I can't use stateful Sanctum logins so Laravel Breeze is a no-go. From the docs it looks like I need to use Sanctum's token login. Does this package support that? Do you have any advice?

**Comment by koole** [comment]
If I understand you correctly, your use case should work just fine with react-sanctum! It's used often for react apps running on different domains from the API.

**Comment by CitizenBeta** [comment]
Does it use tokens though, or is it cookies? According to the docs that doesnt work cross-domain. I could be wrong though?

**Comment by koole** [comment]
It uses tokens and stores these in cookies. Actually you're right, this won't work easily across domains, only subdomains
