### ISSUE TITLE
React peer requirement not recognized

### ISSUE THREAD

**Issue by CitizenBeta** [koole/react-sanctum#6]
When I run npm update, I get these warnings:

> npm WARN react-sanctum@1.0.0 requires a peer of react@^16.13.0 but none is installed. You must install peer dependencies yourself.
> npm WARN react-sanctum@1.0.0 requires a peer of react-dom@^16.13.0 but none is installed. You must install peer dependencies yourself.

This is my package.json:

> "dependencies": {
>     "axios": "^0.21.0",
>     "next": "10.0.0",
>     "next-images": "^1.6.2",
>     "react": "17.0.1",
>     "react-dom": "17.0.1",
>     "react-icons": "^3.11.0",
>     "react-sanctum": "^1.0.0"
>   },
>   "devDependencies": {
>     "@fullhuman/postcss-purgecss": "^3.0.0",
>     "@types/node": "^14.14.6",
>     "@types/react": "^16.9.55",
>     "@typescript-eslint/eslint-plugin": "^4.6.1",
>     "@typescript-eslint/parser": "^4.6.1",
>     "autoprefixer": "^10.0.1",
>     "babel-eslint": "^10.1.0",
>     "eslint": "^7.12.1",
>     "eslint-config-airbnb": "^18.2.0",
>     "eslint-config-airbnb-typescript": "^12.0.0",
>     "eslint-config-react-app": "^6.0.0",
>     "eslint-plugin-flowtype": "^5.2.0",
>     "eslint-plugin-import": "^2.22.1",
>     "eslint-plugin-jsx-a11y": "^6.4.1",
>     "eslint-plugin-promise": "^4.2.1",
>     "eslint-plugin-react": "^7.21.5",
>     "eslint-plugin-react-hooks": "^4.2.0",
>     "postcss-flexbugs-fixes": "^5.0.0",
>     "postcss-preset-env": "^6.7.0",
>     "sass": "^1.28.0",
>     "tailwindcss": "^1.9.6",
>     "typescript": "^4.0.5"
>   },

This should fulfill it, right?

>     "react": "17.0.1",
>     "react-dom": "17.0.1",

**Comment by koole** [comment]
You're right, that should fulfil it. The issue must be that I've only set it to support version 16 of react, but it works fine in 17. I'll update the peer dependencies and release a new version soon. Thanks!

**Comment by CitizenBeta** [comment]
Awesome, thanks for this awesome package! Definitely helps to wrap my head around Sanctum in React.

**Comment by koole** [comment]
This should now be fixed in react-sanctum 1.0.1! Glad to hear this package is helping you out 👍
