### ISSUE TITLE
Is this packade is only for SPA (csrfCookie) not for Mobile Apps (Token) ?

### ISSUE THREAD

**Issue by hotgeart** [koole/react-sanctum#89]
Hi,

I'm building a mobile app and I would like to use this package, but it looks like it's only to be used with csrfCookie. We cannot make it works for Sanctum Token ?

**Comment by koole** [comment]
Yes, you are correct. I know some people have modified this package for use in their React Native apps, but these are unfortunately not open source.

It shouldn't be too hard to modify the code to not use cookies, however I haven't done this before myself so I'm afraid I can't help you with that part.
